/**
 * The single project-wide component library.
 *
 * Two kinds of file live here, told apart by filename case:
 *
 *  - `lowercase.tsx`  — generated by the shadcn CLI (`npx shadcn@latest add x`).
 *                       Re-running the CLI overwrites them, so avoid heavy edits.
 *  - `PascalCase.tsx` — hand-written, still completely domain-free: things
 *                       shadcn does not provide, or that wrap a primitive with
 *                       an API this app needs.
 *
 * Anything that names a domain concept (order, seller, refund…) belongs in
 * `features/<domain>/components` instead — not here.
 */

// shadcn primitives
export * from "./avatar";
export * from "./button";
export * from "./dialog";
export * from "./input";
export * from "./label";
export * from "./table";
export * from "./textarea";

// Hand-written, domain-free
export { AvatarOrInitials } from "./AvatarOrInitials";
export { ConfirmDialogProvider, useConfirm } from "./ConfirmDialog";
export { ConfirmWithReasonDialog } from "./ConfirmWithReasonDialog";
export { LoadingBlock, LoadingState, Spinner, Loading } from "./Loading";
export type { SpinnerProps } from "./Loading";
export { default as Pagination } from "./Pagination";
export { CardSkeleton, Skeleton, TableSkeleton } from "./Skeleton";
export { ToneBadge, type StatusTone } from "./ToneBadge";
export type { SkeletonProps } from "./Skeleton";

export { useToast } from "../providers/ToastProvider";
